server:
  port: 8080

spring:
  segurity:
    oauth2:
      resourceserver:
        jwt:
          secret: dfgrt34dgdfg
          issuer-uri: http://localhost:8081/auth/realms/myrealm

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1

        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1

        - id: transaction-service
          uri: http://localhost:8084
          predicates:
            - Path=/transaction/**
          filters:
            - StripPrefix=1

        - id: credit-service
          uri: http://localhost:8085
          predicates:
            - Path=/credit/**
          filters:
            - StripPrefix=1

      # Configuración CORS global
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

# Logging detallado para Gateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO

# Actuator habilitado para inspección de rutas
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always